development:
  adapter: postgresql
  database: ugpapi2  # Careful not to conflict with the existing database
  port: 5432
  host: 127.0.0.1
  username: ugpapi2
  pool: 1  # This is just for migrations, we should never need more than one connection
  